learning_site/learning_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework import routers
from . import views
from courses import views as view


router = routers.SimpleRouter()
router.register('courses', view.CourseViewSet)
router.register('step', view.StepViewSet)

urlpatterns = [
    path('courses/', include(('courses.url', 'courses'), namespace='courses')),
    path('admin/', admin.site.urls),
    path('', views.index),
    
    path('auth/', include(('rest_framework.urls', 'rest_framework'), namespace='rest_framework')),
    path('api/v1/courses/', include(('courses.url', 'courses_api'), namespace='courses_api')),
    path('api/v2/', include((router.urls, 'courses_v2_api'), namespace='courses_v2_api')),
]

urlpatterns += staticfiles_urlpatterns()

learning_site/courses/models.py
from django.db import models

# Create your models here.


class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    content = models.TextField()
    course = models.ForeignKey(Course,  on_delete=models.CASCADE, related_name='steps')

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.title

learning_site/courses/views.py
from django.shortcuts import get_object_or_404, render
from rest_framework import generics, viewsets, mixins, permissions
from rest_framework.decorators import detail_route
from rest_framework.response import Response
from .models import Course, Step
from .serializers import StepSerializer, CourseSerializer

# Create your views here.


def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})


def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})


def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})


class CourseListCreateView(generics.ListCreateAPIView):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer

class CourseRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer

class StepListCreateView(generics.ListCreateAPIView):
    serializer_class = StepSerializer

    def get_queryset(self):
       return Step.objects.all().filter(course_id=self.kwargs.get('course_pk'))

    def perform_create(self, serializer):
        course = get_object_or_404(
            Course, pk=self.kwargs.get('course_pk')
        )
        serializer.save(course=course)


class StepRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
   queryset = Step.objects.all()
   serializer_class = StepSerializer

   def get_object(self):
       return get_object_or_404(
           Step,
           course_id=self.kwargs.get('course_pk'),
           pk=self.kwargs.get('pk')
       )

class IsSuperUser (permissions.BasePermission):
    def has_permission(self, request, view):
        if not request.user.is_superuser and request.method == 'DELETE':
          return False
        else:
          return True

class CourseViewSet(viewsets.ModelViewSet):
    permission_classes = (
        IsSuperUser,
        permissions.DjangoModelPermissions,)
    queryset = Course.objects.all()
    serializer_class = CourseSerializer
    
    @detail_route(methods=['get'])
    def steps(self, request, pk=None):
        self.pagination_class.page_size = 1
        steps = Step.objects.filter(course_id=pk)
        page = self.paginate_queryset(steps)
        if page is not None:
            serializer = StepSerializer(
               page, many=True
            )
            return self.get_paginated_response(serializer.data)
        serializer = StepSerializer(
               steps, many=True
            )
        return Response(serializer.data)
 
class StepViewSet(mixins.CreateModelMixin,
                    mixins.RetrieveModelMixin,
                    mixins.UpdateModelMixin,
                    mixins.DestroyModelMixin,
                    viewsets.GenericViewSet):
    queryset = Step.objects.all()
    serializer_class = StepSerializer





    

learning_site/learning_site/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home.html')

learning_site/courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %} {{ course.title }} {% endblock %}

{% block content %}

<article bg-info>
    <div class="card col mx-auto mt-5">
        <div class="card-header">
            <p class="text-info">{{course.title}}</p>
        </div>

        <div class="card-body">
            <p class="text-info">{{ course.description }}</p>
            <p class="text-info">{% for step in course.step_set.all %}</p>
        <br/>
            <p>
                <a class="text-info" href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}">{{step.title}}</a></p>
        <p class="text-info">{{step.description}}</p>
        {% endfor %}
        </div>
    </div>
</article>
{% endblock %}

learning_site/courses/templates/courses/course_list.html
{% extends 'layout.html' %}

{% block title %}Available Courses{% endblock %}

{% block content %}



             {% for course in courses %}
            <div class="card col-sm-3 mx-auto mt-5 ">
            <div class=" card-header h-50">
                <p><a  class="text-info" href="{% url 'courses:detail' pk=course.pk %}">{{course.title}}</a></p>
            </div>
            <div class="card-body">
                <p class="text-info">{{course.description}}</p>

            </div>
            </div>
             {% endfor %}



{% endblock %}

learning_site/courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block title %} {{ step.title }}-{{step.course.title}} {% endblock %}

{% block content %}

<div class="card col-sm-3 mx-auto mt-5 ">
    <div class=" card-header h-50">
    <p class="text-info">
        {{step.course.title}}
    </p>
    </div>
    <div class="card-body">
        <p class="text-info">{{ step.title }}</p>
    </div>
   {{ step.content }}
</div>
{% endblock %}

learning_site/templates/home.html
{% extends 'layout.html' %}

{% block title %}welcome dear{% endblock  %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}

learning_site/templates/layout.html
{% load static from staticfiles %}

<!doctype html>

<html>
    <head>
        <title>
            {% block title %}{% endblock %}
        </title>
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    </head>
        <body class="m-5 w-75 h-25 mx-auto container-fluid ">
            <nav class="bg-info">
                <a class="text-light ml-5" href="{% url 'courses:list' %}">Courses</a>
            </nav>
            <div class=" text-white text-center row mx-auto">
                {% block content %}{% endblock %}
            </div>

            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
        </body>
</html>